# Generated by Django 5.1.2 on 2025-09-16 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Healthcare', '0002_alter_appointment_patient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='specialist',
            field=models.CharField(choices=[('cardiologist', 'Cardiologist'), ('gastroenterologist', 'Gastroenterologist'), ('orthopedic', 'Orthopedic Surgeon'), ('general_physician', 'General Physician'), ('neurologist', 'Neurologist'), ('dermatologist', 'Dermatologist')], default='Select', max_length=50),
        ),
    ]
