# Generated by Django 5.1.2 on 2025-09-16 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Healthcare', '0003_alter_appointment_specialist'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('visited', 'Visited'), ('not_visited', 'Not Visited')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='specialist',
            field=models.CharField(choices=[('cardiologist', 'Cardiologist'), ('gastroenterologist', 'Gastroenterologist'), ('orthopedic', 'Orthopedic Surgeon'), ('general_physician', 'General Physician'), ('neurologist', 'Neurologist'), ('dermatologist', 'Dermatologist')], max_length=50),
        ),
    ]
