# Generated by Django 5.1.2 on 2025-09-17 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Healthcare', '0004_appointment_status_alter_appointment_specialist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='time_slot',
            field=models.CharField(choices=[('morning', 'Morning (9 AM - 12 PM)'), ('afternoon', 'Afternoon (1.30 PM - 4 PM)'), ('evening', 'Evening (6 PM - 9 PM)')], default='morning', max_length=20),
        ),
    ]
