# Generated by Django 5.1.2 on 2025-09-17 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Healthcare', '0005_alter_appointment_time_slot'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='consultation_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
